services:
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres

  rabbitmq:
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: carat
      RABBITMQ_DEFAULT_PASS: devpassword123
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: " "

  admin-portal:
    build: { context: ., dockerfile: apps/admin-portal/Dockerfile }
    pull_policy: never
    volumes: [./apps/admin-portal:/app/apps/admin-portal]
    command: pnpm dev

  user-service:
    build: { context: ., dockerfile: apps/user-auth/Dockerfile }
    pull_policy: never
    volumes: [./apps/user-auth:/app/apps/user-auth]
    command: pnpm dev

  catalogue-service:
    build: { context: ., dockerfile: apps/catalogue/Dockerfile }
    pull_policy: never
    volumes: [./apps/catalogue:/app/apps/catalogue]
    command: pnpm dev

  auction-engine:
    build: { context: ., dockerfile: apps/auction-engine/Dockerfile }
    pull_policy: never
    volumes: [./apps/auction-engine:/app/apps/auction-engine]
    command: pnpm dev

  payment-service:
    build: { context: ., dockerfile: apps/payment/Dockerfile }
    pull_policy: never
    volumes: [./apps/payment:/app/apps/payment]
    command: pnpm dev

  notification-service:
    build: { context: ., dockerfile: apps/notification-service/Dockerfile }
    pull_policy: never
    volumes: [./apps/notification-service:/app/apps/notification-service]
    command: pnpm dev

  shipping-service:
    build: { context: ., dockerfile: apps/shipping/Dockerfile }
    pull_policy: never
    volumes: [./apps/shipping:/app/apps/shipping]
    command: pnpm dev

  admin-service:
    build: { context: ., dockerfile: apps/admin/Dockerfile }
    pull_policy: never
    volumes: [./apps/admin:/app/apps/admin]
    command: pnpm dev
