sonar.projectKey=sithwin_bidding-room
sonar.organization=sithwin
sonar.sources=apps,packages
sonar.exclusions=**/dist/**,**/node_modules/**,**/migrations/**,**/coverage/**,**/*.config.ts,**/.next/**
sonar.tests=apps,packages
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=apps/*/coverage/lcov.info,packages/*/coverage/lcov.info
