CREATE DATABASE users;
CREATE DATABASE catalogue;
CREATE DATABASE auction_engine;
CREATE DATABASE payments;
CREATE DATABASE notifications;
CREATE DATABASE shipping;

GRANT ALL PRIVILEGES ON DATABASE users TO postgres;
GRANT ALL PRIVILEGES ON DATABASE catalogue TO postgres;
GRANT ALL PRIVILEGES ON DATABASE auction_engine TO postgres;
GRANT ALL PRIVILEGES ON DATABASE payments TO postgres;
GRANT ALL PRIVILEGES ON DATABASE notifications TO postgres;
GRANT ALL PRIVILEGES ON DATABASE shipping TO postgres;
