apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-and-email
    receivers:
      - uid: slack-receiver
        type: slack
        settings:
          url: '${SLACK_WEBHOOK_URL}'
      - uid: email-receiver
        type: email
        settings:
          addresses: '${ALERT_EMAIL_TO}'

policies:
  - orgId: 1
    receiver: slack-and-email
    group_by: ['alertname', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
